// ============================================
// HydraFlow — Shared Enums & Constants
// Used by both client and server
// ============================================

export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANUFACTURER_USER: 'MANUFACTURER_USER',
  DEALER_USER: 'DEALER_USER',
  SERVICE_ENGINEER: 'SERVICE_ENGINEER',
  CUSTOMER: 'CUSTOMER',
};

export const COMPANY_TYPES = {
  MANUFACTURER: 'MANUFACTURER',
  DEALER: 'DEALER',
  SERVICE_PROVIDER: 'SERVICE_PROVIDER',
};

export const COMPANY_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DEACTIVATED: 'DEACTIVATED',
};

export const SUBSCRIPTION_PLANS = {
  BASIC: 'BASIC',
  PROFESSIONAL: 'PROFESSIONAL',
  ENTERPRISE: 'ENTERPRISE',
};

export const PUMP_STATUS = {
  IN_FACTORY: 'IN_FACTORY',
  IN_TRANSIT: 'IN_TRANSIT',
  AT_DEALER: 'AT_DEALER',
  SOLD: 'SOLD',
  INSTALLED: 'INSTALLED',
  DECOMMISSIONED: 'DECOMMISSIONED',
};

export const PRODUCT_STATUS = {
  ACTIVE: 'ACTIVE',
  DISCONTINUED: 'DISCONTINUED',
  DRAFT: 'DRAFT',
};

export const ORDER_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  CONFIRMED: 'CONFIRMED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

export const PAYMENT_METHODS = {
  CASH: 'CASH',
  UPI: 'UPI',
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  FINANCING: 'FINANCING',
};

export const INSTALLATION_STATUS = {
  REQUESTED: 'REQUESTED',
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  VERIFIED: 'VERIFIED',
  CANCELLED: 'CANCELLED',
};

export const INSTALLATION_TYPES = {
  NEW: 'NEW',
  REPLACEMENT: 'REPLACEMENT',
  RELOCATION: 'RELOCATION',
};

export const POWER_SUPPLY_TYPES = {
  SINGLE_PHASE: 'SINGLE_PHASE',
  THREE_PHASE: 'THREE_PHASE',
  SOLAR: 'SOLAR',
};

export const WARRANTY_TYPES = {
  STANDARD: 'STANDARD',
  EXTENDED: 'EXTENDED',
  PREMIUM: 'PREMIUM',
};

export const WARRANTY_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  VOIDED: 'VOIDED',
  CLAIMED: 'CLAIMED',
};

export const CLAIM_TYPES = {
  REPAIR: 'REPAIR',
  REPLACEMENT: 'REPLACEMENT',
  REFUND: 'REFUND',
};

export const CLAIM_STATUS = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  RESOLVED: 'RESOLVED',
};

export const AMC_PLANS = {
  BASIC: 'BASIC',
  SILVER: 'SILVER',
  GOLD: 'GOLD',
  PLATINUM: 'PLATINUM',
};

export const AMC_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  RENEWED: 'RENEWED',
};

export const TICKET_TYPES = {
  REPAIR: 'REPAIR',
  MAINTENANCE: 'MAINTENANCE',
  INSPECTION: 'INSPECTION',
  INSTALLATION: 'INSTALLATION',
  WARRANTY_CLAIM: 'WARRANTY_CLAIM',
};

export const TICKET_PRIORITY = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
};

export const TICKET_STATUS = {
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  EN_ROUTE: 'EN_ROUTE',
  IN_PROGRESS: 'IN_PROGRESS',
  PENDING_PARTS: 'PENDING_PARTS',
  COMPLETED: 'COMPLETED',
  SIGNED_OFF: 'SIGNED_OFF',
  CANCELLED: 'CANCELLED',
};

export const PHOTO_PHASES = {
  BEFORE: 'BEFORE',
  DURING: 'DURING',
  AFTER: 'AFTER',
};

export const IOT_CONNECTIVITY = {
  FOUR_G: '4G',
  WIFI: 'WIFI',
  LORA: 'LORA',
  SATELLITE: 'SATELLITE',
};

export const IOT_DEVICE_STATUS = {
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  MAINTENANCE: 'MAINTENANCE',
  FAULTY: 'FAULTY',
};

export const ALERT_TYPES = {
  OVER_TEMP: 'OVER_TEMP',
  LOW_PRESSURE: 'LOW_PRESSURE',
  OVER_VOLTAGE: 'OVER_VOLTAGE',
  DRY_RUN: 'DRY_RUN',
  HIGH_VIBRATION: 'HIGH_VIBRATION',
  OFFLINE: 'OFFLINE',
  ANOMALY: 'ANOMALY',
};

export const ALERT_SEVERITY = {
  CRITICAL: 'CRITICAL',
  WARNING: 'WARNING',
  INFO: 'INFO',
};

export const ALERT_OPERATORS = {
  GT: 'GT',
  LT: 'LT',
  GTE: 'GTE',
  LTE: 'LTE',
  EQ: 'EQ',
};

export const NOTIFICATION_TYPES = {
  SERVICE_UPDATE: 'SERVICE_UPDATE',
  IOT_ALERT: 'IOT_ALERT',
  WARRANTY_EXPIRY: 'WARRANTY_EXPIRY',
  ORDER_STATUS: 'ORDER_STATUS',
  SYSTEM: 'SYSTEM',
  PROMOTION: 'PROMOTION',
};

export const NOTIFICATION_CHANNELS = {
  IN_APP: 'IN_APP',
  PUSH: 'PUSH',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
};

export const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  STATUS_CHANGE: 'STATUS_CHANGE',
};

export const FIELD_INVENTORY_CATEGORIES = {
  SPARE_PART: 'SPARE_PART',
  TOOL: 'TOOL',
  CONSUMABLE: 'CONSUMABLE',
};

// Role-based portal mapping
export const ROLE_PORTAL_MAP = {
  [USER_ROLES.SUPER_ADMIN]: '/global-ops',
  [USER_ROLES.ADMIN]: '/admin',
  [USER_ROLES.MANUFACTURER_USER]: '/manufacturer',
  [USER_ROLES.DEALER_USER]: '/dealer',
  [USER_ROLES.SERVICE_ENGINEER]: '/service',
  [USER_ROLES.CUSTOMER]: '/customer',
};

// Role hierarchy for RBAC
export const ROLE_HIERARCHY = {
  [USER_ROLES.SUPER_ADMIN]: 6,
  [USER_ROLES.ADMIN]: 5,
  [USER_ROLES.MANUFACTURER_USER]: 4,
  [USER_ROLES.DEALER_USER]: 3,
  [USER_ROLES.SERVICE_ENGINEER]: 2,
  [USER_ROLES.CUSTOMER]: 1,
};
